### ISSUE TITLE
Documentation fixes

### ISSUE THREAD

**Issue by g-bauer** [feos-org/feos-core#23]
Issue to collect typos in docs.

## Typos

- [x]  "wer~~de~~ used" [`Parameter.records` method](https://docs.rs/feos-core/0.1.2/feos_core/parameter/trait.Parameter.html#tymethod.records)

## Python
*Missing `text_signature`, typos, etc.*

**Comment by prehner** [comment]
- [ ] `DataSet.equilibrium_liquid_density`

**Comment by prehner** [comment]
- [ ] Partial derivative of chemical potential w.r.t. moles:
